realestateApi/realestate/urls.py
from django.urls import path

from . import views

app_name = "realestate"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:property_id>/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("create/submit", views.submit, name="submit"),
]

realestateApi/realestateApi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("realestate/", include("realestate.urls")),
    path("admin/", admin.site.urls),
]

realestateApi/realestate/models.py
from django.db import models


class Property(models.Model):
    address_number = models.IntegerField(default=0)
    address_street = models.CharField(max_length=200)
    address_city = models.CharField(max_length=200)
    parcel_id = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    zoning = models.CharField(max_length=200)
    sale_date = models.CharField(max_length=200)
    sale_price = models.CharField(max_length=200)
    legal_reference = models.CharField(max_length=200)
    seller = models.CharField(max_length=200)
    assessment_year = models.CharField(max_length=200)
    land_area = models.CharField(max_length=200)
    building_value = models.CharField(max_length=200)
    extra_features_value = models.CharField(max_length=200)
    land_value = models.CharField(max_length=200)
    total_value = models.CharField(max_length=200)
    narrative_description = models.CharField(max_length=200)
    last_updated = models.DateTimeField("date published")

    def __str__(self):
        return "%s %s" % (self.address_number, self.address_street)

realestateApi/realestate/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.http import HttpResponse
from django.views import generic
from .models import Property
from datetime import datetime

# Create your views here.


class IndexView(generic.ListView):
    template_name = "realestate/index.html"
    context_object_name = "realestate_list"

    def get_queryset(self):
        """
        Return property data
        """
        return Property.objects.all()


def detail(request, property_id):
    try:
        property = Property.objects.get(pk=property_id)
    except Property.DoesNotExist:
        raise Http404("Property does not exist")
    return render(request, "realestate/detail.html", {"property": property})


def create(request):
    return render(request, "realestate/create.html")


def submit(request):
    address_number = request.POST["address_number"]
    address_street = request.POST["address_street"]
    last_updated = datetime.now()
    property = Property(
        address_number=address_number,
        address_street=address_street,
        last_updated=last_updated,
    )
    property.save()
    return HttpResponseRedirect("/realestate/")

realestateApi/realestate/templates/realestate/create.html
<form action="{% url 'realestate:submit' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Create A property</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        
        <label for="address_number">address number:</label><br>
        <input type="text" id="address_number" name="address_number" value="{{ input_address_number }}"><br>
        
        <label for="address_street">address_street:</label><br>
        <input type="text" id="address_street" name="address_street" value="{{ input_address_street }}"><br><br>
        
        <label for="address_city">address_city:</label><br>
        <input type="text" id="address_city" name="address_city" value="{{ input_address_city }}"><br><br>
        
        <label for="parcel_id">parcel_id:</label><br>
        <input type="text" id="parcel_id" name="parcel_id" value="{{ input_parcel_id }}"><br><br>
        
        <label for="owner">owner:</label><br>
        <input type="text" id="owner" name="owner" value="{{ input_owner }}"><br><br>
        
        <label for="zoning">zoning:</label><br>
        <input type="text" id="zoning" name="zoning" value="{{ input_zoning }}"><br><br>
        
        <label for="sale_date">sale_date:</label><br>
        <input type="text" id="sale_date" name="sale_date" value="{{ input_sale_date }}"><br><br>
        
        <label for="sale_price">sale_price:</label><br>
        <input type="text" id="sale_price" name="sale_price" value="{{ input_sale_price }}"><br><br>

        <label for="legal_reference">legal_reference:</label><br>
        <input type="text" id="legal_reference" name="legal_reference" value="{{ input_legal_reference }}"><br><br>
        
        <label for="seller">seller:</label><br>
        <input type="text" id="seller" name="seller" value="{{ input_seller }}"><br><br>
        
        <label for="assessment_year">assessment_year:</label><br>
        <input type="text" id="assessment_year" name="assessment_year" value="{{ input_assessment_year }}"><br><br>
        
        <label for="land_area">land_area:</label><br>
        <input type="text" id="land_area" name="land_area" value="{{ input_land_area }}"><br><br>

        <label for="building_value">building_value:</label><br>
        <input type="text" id="building_value" name="building_value" value="{{ input_building_value }}"><br><br>

        <label for="extra_features_value">extra_features_value:</label><br>
        <input type="text" id="extra_features_value" name="extra_features_value" value="{{ input_extra_features_value }}"><br><br>

        <label for="land_value">land_value:</label><br>
        <input type="text" id="land_value" name="land_value" value="{{ input_land_value }}"><br><br>

        <label for="total_value">total_value:</label><br>
        <input type="text" id="total_value" name="total_value" value="{{ input_total_value }}"><br><br>

        <label for="narrative_description">narrative_description:</label><br>
        <input type="text" id="narrative_description" name="narrative_description" value="{{ input_narrative_description }}"><br><br>

        <label for="last_updated">last_updated:</label><br>
        <input type="text" id="last_updated" name="last_updated" value="{{ input_last_updated }}"><br><br>

    </fieldset>
    <input type="submit" value="Submit">
</form>

realestateApi/realestate/templates/realestate/detail.html
<div style="padding:5% 10%">
    <h2>{{ property.address_number }} {{ property.address_street }}</h2>
</div>

realestateApi/realestate/templates/realestate/index.html
{% if realestate_list %}
<ul>
{% for realestate in realestate_list %}
    <li><a href="{% url 'realestate:detail' realestate.pk %}">{{ realestate.address_number }} {{ realestate.address_street }}</a></li>

{% endfor %}
<div>
    <a href="{% url 'realestate:create' %}">create realestate</a>
</div>
</ul>
{% else %}
<p>No Realestate is here.</p>
{% endif %}